### ISSUE TITLE
core down in 'r3_route_attribute_free'

### ISSUE THREAD

**Issue by yang282441848** [iresty/lua-resty-libr3#32]
It happened several times but I cannot recover this exactly scence. 
```
warning: core file may not match specified executable file.
[New LWP 6]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `nginx: worker process is shutting'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  r3_route_attribute_free (router=0x7fc1dbc21170) at r3_resty.c:70
70      r3_resty.c: No such file or directory.
(gdb) bt
#0  r3_route_attribute_free (router=0x7fc1dbc21170) at r3_resty.c:70
#1  0x00007fc1da104046 in ?? () from /usr/local/openresty/luajit/lib/libluajit-5.1.so.2
#2  0x00007fc1da14800c in ?? () from /usr/local/openresty/luajit/lib/libluajit-5.1.so.2
#3  0x00007fc1da15d137 in ?? () from /usr/local/openresty/luajit/lib/libluajit-5.1.so.2
#4  0x00007fc1da101a75 in ?? () from /usr/local/openresty/luajit/lib/libluajit-5.1.so.2
#5  0x00007fc1da1041c3 in ?? () from /usr/local/openresty/luajit/lib/libluajit-5.1.so.2
#6  0x00007fc1da104297 in ?? () from /usr/local/openresty/luajit/lib/libluajit-5.1.so.2
#7  0x00007fc1da105348 in ?? () from /usr/local/openresty/luajit/lib/libluajit-5.1.so.2
#8  0x00007fc1da10c0c1 in ?? () from /usr/local/openresty/luajit/lib/libluajit-5.1.so.2
#9  0x00007fc1da101e6b in ?? () from /usr/local/openresty/luajit/lib/libluajit-5.1.so.2
#10 0x00007fc1da10c3e2 in lua_close () from /usr/local/openresty/luajit/lib/libluajit-5.1.so.2
#11 0x00007fc1dad0e14c in ngx_http_lua_cleanup_vm ()
#12 0x00007fc1dac35536 in ngx_destroy_pool ()
#13 0x00007fc1dac5b1a3 in ?? ()
#14 0x00007fc1dac5b327 in ?? ()
#15 0x00007fc1dac59ac8 in ngx_spawn_process ()
#16 0x00007fc1dac5b770 in ?? ()
---Type <return> to continue, or q <return> to quit---
#17 0x00007fc1dac5c1bd in ngx_master_process_cycle ()
#18 0x00007fc1dac32dfd in main ()
```

**Comment by membphis** [comment]
it may fixed https://github.com/iresty/lua-resty-libr3/commit/4beef69ec97575c020448ac11c5fce733ad5f322#diff-33eefcde40c3fb7b556c5b81239c365cR133, you can get the latest version manually. I'll try to add more test to check it.
